### ISSUE TITLE
decide which pages and its functions we want on the website

### ISSUE THREAD

**Issue by evanye1202** [CSAllenISD/2023-ISP-CodeConverter#11]

**Comment by Zaenb** [comment]
yes, l believe we definitely have to do that in order to proceed and start the code that is why we need to call and share our ideas as a group

**Comment by KarthikPeravali** [comment]
Different website platforms are a huge way to discuss  plan for a html webpage. Once picking a certain webpage style, can we move on to the specail variances in our converter
