### ISSUE TITLE
Proper opening of issues

### ISSUE THREAD

**Issue by VivekMaranganti** [CSAllenISD/2023-ISP-CodeConverter#14]
The use of GitHub Projects for our issues is not working too well for us at the moment. We have to figure out, as a group, how to properly use it in a way that all opened issues show up in both the repository and the GitHub projects view.

**Comment by neeraj-gogate** [comment]
The problem with issues not showing up here has been fixed, all you need to do is make sure you specify the project on the issue when you make it in the repository. We'll close if it goes well for a week.
