### ISSUE TITLE
As we are working in two separate files—one for the front end and one for the back end—I think we need to merge them in order to ensure that everything is proceeding as planned, to ensure that everything will function together, and to begin testing it.

### ISSUE THREAD

**Issue by Zaenb** [CSAllenISD/2023-ISP-CodeConverter#37]

**Comment by janadaouk** [comment]
I agree. We need to fix and organize our branches.

**Comment by VivekMaranganti** [comment]
I believe the front end and back end should stay in separate files, but be merged into the same branch eventually. However, the backend code is in 2 separate branches and should be merged as soon as our input method is functional.

**Comment by neeraj-gogate** [comment]
I am unsure of what you mean by different files, there is no real way to merge the c++ code and HTML/css side together into one file. Are you suggesting we start testing c++ on the website?

**Comment by Zaenb** [comment]
Oh ya, l mean that we should test C++ to make sure it works and add whatever is needed to make it work.
