### ISSUE TITLE
About Me page is not functional

### ISSUE THREAD

**Issue by VivekMaranganti** [CSAllenISD/2023-ISP-CodeConverter#95]
Everything is cramped into the header and formatting of necessary elements is broken.
<img width="2537" alt="Screen Shot 2023-04-27 at 12 08 36 PM" src="https://user-images.githubusercontent.com/111006489/234937750-933abdfc-3015-4db3-9f2f-bd7a86db5d31.png">

**Comment by janadaouk** [comment]
It looked good last week, someone changed it. I'll fix it again. Thank you for sharing! 👍
